/**
 * Created by 178063117 on 2017/9/29.
 */
export const RECEIVE_COMMENTS_COUNT='RECEIVE_COMMENTS_COUNT'
export const RECEIVE_LIKES_COUNT = 'RECEIVE_LIKES_COUNT'
export const RECEIVE_TODAY_COMMENTS = 'RECEIVE_TODAY_COMMENTS'
export const RECEIVE_TODAY_LIKES = 'RECEIVE_TODAY_LIKES'

